### ISSUE TITLE
code execution backdoor

### ISSUE THREAD

**Issue by di1l0o** [SunnyHaze/SCU-Captcha#1]
We found a malicious backdoor in versions 0.0.1~0.0.4 of this project, and its malicious backdoor is the request package. Even if the request package was removed by pypi, many mirror sites did not completely delete this package, so it could still be installed.When using  pip install scu-captcha -i http://pypi.doubanio.com/simple --trusted-host pypi.doubanio.com, the request malicious plugin can be successfully installed.

![image](https://user-images.githubusercontent.com/58363074/176375958-bdf24672-3845-489b-9217-728da9c955b7.png)

Repair suggestion: delete version 0.0.1~0.0.4 in PyPI, replace request with requests

**Comment by SunnyHaze** [comment]
Thank you for mentioning this bug, and I'm sorry for the inconvenience caused by my negligence.

I was busy a while ago. Finally I have time to revise these two days. Please forgive for the defer.

The dependency bug has solved now! Thank you again, and Wish you good luck !
